using Bitstream.Domain.Enums;

namespace Bitstream.Application.Identity.Entities;

/// <summary>
/// A pending second-factor verification, TR-SEC-04.
/// <para>
/// Not a TRD 3.1 entity — added because "the second factor must be a time-based one-time code
/// (TOTP or SMS/email OTP), valid for a maximum of 5 minutes and usable once" needs somewhere
/// to hold the state between the first-factor password check and the second-factor code
/// submission, across two separate HTTP requests and potentially two application-pool worker
/// processes (TR-NFR-03 sizes the portal for 200 concurrent users behind IIS, which is free to
/// run more than one worker process). An in-memory challenge would not survive that.
/// </para>
/// <para>
/// For <see cref="TwoFactorChannel.Totp"/> there is no code to store here: the code is
/// generated by the user's authenticator app from <see cref="User.TotpSecret"/> and is verified
/// directly against it, so <see cref="CodeHash"/> is null for that channel. For
/// <see cref="TwoFactorChannel.EmailOtp"/> and <see cref="TwoFactorChannel.SmsOtp"/> the portal
/// generates the code itself, so only its hash is stored — the same reasoning as a password
/// hash: a copy of this table must not hand out a usable code.
/// </para>
/// <para>
/// Moved out of <c>Bitstream.Domain</c> alongside <see cref="User"/> purely because it navigates
/// to it — the table itself (<c>sec.TwoFactorChallenge</c>) stays hand-written, unmigrated.
/// </para>
/// </summary>
public sealed class TwoFactorChallenge
{
    public long ChallengeId { get; set; }

    /// <summary>Opaque token returned to the caller after the first factor succeeds. The lookup key; unique.</summary>
    public required string ChallengeToken { get; set; }

    public long UserId { get; set; }

    public User User { get; set; } = null!;

    public TwoFactorChannel Channel { get; set; }

    /// <summary>Hash of the one-time code. Null for <see cref="TwoFactorChannel.Totp"/>.</summary>
    public string? CodeHash { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>At most 5 minutes after <see cref="CreatedAt"/> (TR-SEC-04).</summary>
    public DateTimeOffset ExpiresAt { get; set; }

    /// <summary>Set once verification succeeds. A consumed challenge can never be verified again — "usable once".</summary>
    public DateTimeOffset? ConsumedAt { get; set; }

    /// <summary>Failed verification attempts against this challenge; exhausting the budget invalidates it.</summary>
    public int AttemptCount { get; set; }
}
