using Bitstream.Domain.Enums;

namespace Bitstream.Domain.Entities;

/// <summary>
/// Activation request raised by an ISP. TRD 3.1 "ActivationRequest", TRD 5.
/// <see cref="PublicId"/> is the human-readable identifier (<c>^[A-Z]+_[0-9]+$</c>, TR-DAT-02d),
/// generated by the portal before any CRM call (TR-DAT-01) and immutable once issued (TR-DAT-04).
/// </summary>
public sealed class ActivationRequest
{
    public long RequestId { get; set; }

    /// <summary>Unique, immutable, indexed for BI extraction (TR-DAT-05).</summary>
    public required string PublicId { get; set; }

    public long IspId { get; set; }

    public Isp Isp { get; set; } = null!;

    /// <summary>Code from the configurable package catalogue (TR-ACT-01).</summary>
    public required string PackageCode { get; set; }

    /// <summary>Location exactly as entered — map URL or coordinate pair (TR-ACT-02).</summary>
    public required string LocationRaw { get; set; }

    /// <summary>Normalised latitude, -90..90 (TR-ACT-02/03).</summary>
    public decimal LocationLat { get; set; }

    /// <summary>Normalised longitude, -180..180 (TR-ACT-02/03).</summary>
    public decimal LocationLng { get; set; }

    /// <summary>Ticket classification code, default REQUEST_FOR_ACTIVATION (TR-ACT-04).</summary>
    public required string Classification { get; set; }

    /// <summary>12 or 24, from the configured list (TRD 5.1).</summary>
    public int ContractDurationMonths { get; set; }

    /// <summary>Free text, max 2000 characters, HTML stripped (TRD 5.1).</summary>
    public string? Comments { get; set; }

    public ActivationRequestStatus Status { get; set; } = ActivationRequestStatus.Submitted;

    /// <summary>Populated from the CRM response (TR-ACT-10 / TR-INT-18).</summary>
    public string? CrmTicketId { get; set; }

    /// <summary>Populated from the CRM response (TR-ACT-10).</summary>
    public string? CrmCustomerId { get; set; }

    /// <summary>Customer Business Partner transmitted to CRM (TR-ACT-08).</summary>
    public string? Bp { get; set; }

    /// <summary>Sales order reference received on the inbound event API (TR-ACT-18).</summary>
    public string? SalesOrderId { get; set; }

    /// <summary>
    /// SAP ERP financial code. Nullable until populated; its absence must not block the
    /// flow (TR-INT-11 / TR-INT-14). Population point is TRD 11.4 open item 5.
    /// </summary>
    public string? FinancialCode { get; set; }

    /// <summary>Reason recorded when the request is rejected or fails (TR-ACT-13, TR-INT-19).</summary>
    public string? StatusReason { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public long? CreatedBy { get; set; }

    public DateTimeOffset? LastUpdatedAt { get; set; }

    /// <summary>
    /// <c>OccurredAt</c> of the last inbound CRM event actually applied to this request
    /// (TRD 7.3.2). An event older than this is discarded rather than applied (TR-INT-25).
    /// </summary>
    public DateTimeOffset? LastAppliedEventAt { get; set; }
}
